import Head from "next/head";

import Layout from "@/components/Layout";

import Notification from "@/components/Notification";
import dynamic from "next/dynamic";
const Graph = dynamic(() => import("../components/Graph"), { ssr: false });

export default function Home({ courtCases }) {
  const numberOfUndatedCases = courtCases.filter(
    (cases) => cases.casestatus === "undated"
  );

  return (
    <>
      <Head>
        <title>C N Law Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header  */}

      <Layout>
        <div>
          <div>
            <Notification numberOfUndatedCases={numberOfUndatedCases} />
          </div>
          <div>
            <Graph />
          </div>
        </div>
      </Layout>
    </>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch("http://localhost:3000/api/cases", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  const data = await response.json();

  return {
    props: {
      courtCases: data,
    },
  };
};
