import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'; 
import Layout from '@/components/Layout';
import { useRouter } from 'next/router';
import Notification from '@/components/Notification'; 
import Graph from '@/components/Graph'





export default function Home() {

  const router = useRouter();


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {/* Header  */}

     <Layout>
     
     <Notification />

     <Graph />
    
    

     
     </Layout>

     
  
     
    


     



    





    </>
  )
}
